CREATE TABLE IF NOT EXISTS ${database}.${prefix}denizen (
  id BINARY(16) NOT NULL,
  ign VARCHAR(255) NOT NULL,
  quests BIT(3) NOT NULL,
  streak SMALLINT UNSIGNED NOT NULL,
  last_update TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    NOT NULL,
  PRIMARY KEY (id)
)Engine=InnoDB;
