name: DailyStreaks
version: 0.0.1
api-version: '1.20'
description: Encourage users to complete quests daily
main: com.calebpower.mc.dailystreaks.DailyStreaks
depend: [McDbDriver]
commands:
  streak:
    description: Base command for the DailyStreaks plugin
