name: DailyStreaks
version: 0.0.1
api-version: 1.20
description: Encourage users to complete quests daily
main: com.github.calebpower.mc.dailystreaks.DailyStreaks
depend: [McDbDriver, ShopGUIPlus]
commands:
  streak:
    description: Base command for the DailyStreaks plugin
